"""Real PostgreSQL policy/context tests, only on the explicitly named test DB."""
from contextlib import contextmanager
import os
from urllib.parse import urlparse
from uuid import uuid4

from fastapi import FastAPI
from fastapi.testclient import TestClient
import pytest

from api import dependencies
from api.routers import billing
from services import tenant_db


@pytest.fixture
def postgres_database(monkeypatch):
    dsn = os.getenv("MARKETPLACE_HUB_TEST_POSTGRES_DSN")
    if not dsn:
        pytest.skip("Set MARKETPLACE_HUB_TEST_POSTGRES_DSN for the isolated PostgreSQL test service")
    import psycopg
    from psycopg import sql
    from psycopg.rows import dict_row
    parsed = urlparse(dsn)
    assert parsed.hostname in {"127.0.0.1", "localhost"}
    assert parsed.path == "/marketplacehub_test", "Refusing a non-test database"
    schema = "test_scope_" + uuid4().hex
    role = "test_reader_" + uuid4().hex
    monkeypatch.setenv("MARKETPLACE_HUB_DB_ENGINE", "postgresql")
    with psycopg.connect(dsn, autocommit=True) as admin:
        admin.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
        admin.execute(sql.SQL("CREATE ROLE {} NOLOGIN NOSUPERUSER NOBYPASSRLS").format(sql.Identifier(role)))
        try:
            admin.execute(sql.SQL("CREATE TABLE {}.scope_probe (tenant_id BIGINT NOT NULL, value TEXT)").format(sql.Identifier(schema)))
            admin.execute(sql.SQL("INSERT INTO {}.scope_probe VALUES (11,'A'), (22,'B')").format(sql.Identifier(schema)))
            admin.execute(sql.SQL("ALTER TABLE {}.scope_probe ENABLE ROW LEVEL SECURITY").format(sql.Identifier(schema)))
            admin.execute(sql.SQL("ALTER TABLE {}.scope_probe FORCE ROW LEVEL SECURITY").format(sql.Identifier(schema)))
            # Use the actual application's policy expression, not a test approximation.
            expression = sql.SQL(tenant_db._policy_expression())
            admin.execute(sql.SQL("CREATE POLICY tenant_scope ON {}.scope_probe USING ({}) WITH CHECK ({})").format(sql.Identifier(schema), expression, expression))
            admin.execute(sql.SQL("GRANT USAGE ON SCHEMA {} TO {}").format(sql.Identifier(schema), sql.Identifier(role)))
            admin.execute(sql.SQL("GRANT SELECT,INSERT ON {}.scope_probe TO {}").format(sql.Identifier(schema), sql.Identifier(role)))

            @contextmanager
            def connect():
                with psycopg.connect(dsn, row_factory=dict_row) as con:
                    con.execute(sql.SQL("SET ROLE {}").format(sql.Identifier(role)))
                    con.execute(sql.SQL("SET search_path TO {}").format(sql.Identifier(schema)))
                    flags = con.execute("SELECT rolsuper,rolbypassrls FROM pg_roles WHERE rolname=current_user").fetchone()
                    assert flags == {"rolsuper": False, "rolbypassrls": False}

                    class Adapter:
                        def execute(self, query, params):
                            return con.execute(query.replace("?", "%s"), params)

                    tenant_db.apply_postgresql_connection_context(Adapter())
                    yield con
            yield connect
        finally:
            # Both identifiers are generated by this fixture, in the asserted test DB.
            admin.execute(sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(schema)))
            admin.execute(sql.SQL("DROP ROLE {}").format(sql.Identifier(role)))


def test_real_rls_filters_and_rejects_cross_tenant_insert(postgres_database):
    from psycopg.errors import InsufficientPrivilege
    with tenant_db.tenant_database_scope(11):
        with postgres_database() as con:
            assert con.execute("SELECT tenant_id FROM scope_probe").fetchall() == [{"tenant_id": 11}]
        with pytest.raises(InsufficientPrivilege):
            with postgres_database() as con:
                con.execute("INSERT INTO scope_probe VALUES (22,'forbidden')")
    with tenant_db.tenant_database_scope(22):
        with postgres_database() as con:
            assert con.execute("SELECT tenant_id FROM scope_probe").fetchall() == [{"tenant_id": 22}]
    with postgres_database() as con:
        assert con.execute("SELECT tenant_id FROM scope_probe").fetchall() == []
    assert tenant_db.current_tenant_id() == 0


def test_authorized_billing_target_uses_real_rls_scope(postgres_database, monkeypatch):
    monkeypatch.setattr(dependencies, "session_user", lambda token: {
        "id": 1, "active_tenant_id": 11, "tenant_ids": [11, 22],
        "tenant_role": "viewer", "seller_ids": [], "permissions": [],
    })
    def events(tenant_id, **kwargs):
        with postgres_database() as con:
            return con.execute("SELECT tenant_id,value FROM scope_probe WHERE tenant_id=%s", (tenant_id,)).fetchall()
    monkeypatch.setattr(billing, "billing_events", events)
    app = FastAPI()
    app.include_router(billing.router)
    with TestClient(app) as client:
        assert client.get("/tenants/22/billing/events").json() == [{"tenant_id": 22, "value": "B"}]
        assert client.get("/tenants/33/billing/events").status_code == 404
        assert client.get("/tenants/11/billing/events").json() == [{"tenant_id": 11, "value": "A"}]
    assert tenant_db.current_tenant_id() == 0
