from __future__ import annotations

import atexit
import re
import threading
from contextlib import contextmanager
from typing import Any, Iterable

from services.database_config import load_database_config, postgresql_settings

_POOL = None
_POOL_LOCK = threading.RLock()


class PostgreSQLUnavailable(RuntimeError):
    pass


def _require_psycopg():
    try:
        import psycopg  # type: ignore
        from psycopg.rows import dict_row  # type: ignore
        from psycopg_pool import ConnectionPool  # type: ignore
    except ImportError as error:  # pragma: no cover - depends on optional runtime
        raise PostgreSQLUnavailable(
            "PostgreSQL è configurato ma Psycopg non è installato. "
            "Esegui RIPARA_DIPENDENZE_WINDOWS.bat o reinstalla requirements.txt."
        ) from error
    return psycopg, dict_row, ConnectionPool


def _replace_qmark_placeholders(sql: str) -> str:
    """Translate SQLite qmark placeholders to Psycopg %s safely.

    Question marks inside SQL strings, quoted identifiers, and comments are
    preserved.  Marketplace Hub does not use PostgreSQL JSON ``?`` operators,
    so an unquoted question mark is always a parameter marker in our SQL.
    """
    out: list[str] = []
    index = 0
    state = "normal"
    while index < len(sql):
        char = sql[index]
        nxt = sql[index + 1] if index + 1 < len(sql) else ""
        if state == "normal":
            if char == "%":
                # Psycopg uses %-style placeholders.  Marketplace Hub SQL is
                # written for SQLite and contains literal percent signs in
                # LIKE patterns (e.g. '%cancel%') and occasionally formatting
                # masks.  Escape every percent already present in the source
                # SQL; qmark placeholders are converted to %s separately below.
                out.append("%%")
            elif char == "'":
                state = "single"
                out.append(char)
            elif char == '"':
                state = "double"
                out.append(char)
            elif char == "-" and nxt == "-":
                state = "line_comment"
                out.extend((char, nxt))
                index += 1
            elif char == "/" and nxt == "*":
                state = "block_comment"
                out.extend((char, nxt))
                index += 1
            elif char == "?":
                out.append("%s")
            else:
                out.append(char)
        elif state == "single":
            if char == "%":
                out.append("%%")
            else:
                out.append(char)
            if char == "'":
                if nxt == "'":
                    out.append(nxt)
                    index += 1
                else:
                    state = "normal"
        elif state == "double":
            if char == "%":
                out.append("%%")
            else:
                out.append(char)
            if char == '"':
                if nxt == '"':
                    out.append(nxt)
                    index += 1
                else:
                    state = "normal"
        elif state == "line_comment":
            out.append("%%" if char == "%" else char)
            if char == "\n":
                state = "normal"
        elif state == "block_comment":
            out.append("%%" if char == "%" else char)
            if char == "*" and nxt == "/":
                out.append(nxt)
                index += 1
                state = "normal"
        index += 1
    return "".join(out)


def _append_on_conflict_do_nothing(sql: str) -> str:
    stripped = sql.rstrip()
    semicolon = ";" if stripped.endswith(";") else ""
    if semicolon:
        stripped = stripped[:-1].rstrip()
    return f"{stripped} ON CONFLICT DO NOTHING{semicolon}"


def translate_sql(sql: str) -> str:
    """Translate the small SQLite dialect surface used by Marketplace Hub."""
    translated = str(sql)
    translated = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"\bGROUP_CONCAT\s*\(", "STRING_AGG(", translated, flags=re.IGNORECASE
    )
    translated = re.sub(r"\bBLOB\b", "BYTEA", translated, flags=re.IGNORECASE)
    translated = re.sub(
        r"\bINSERT\s+OR\s+IGNORE\s+INTO\b",
        "INSERT INTO",
        translated,
        flags=re.IGNORECASE,
    )
    if re.search(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", str(sql), flags=re.IGNORECASE):
        translated = _append_on_conflict_do_nothing(translated)
    # Legacy usage counters used SQLite's datetime('now', '-N days') helper.
    translated = re.sub(
        r"datetime\s*\(\s*([A-Za-z_][A-Za-z0-9_.]*)\s*\)\s*>=\s*"
        r"datetime\s*\(\s*'now'\s*,\s*\?\s*\)",
        r"\1::timestamptz >= CURRENT_TIMESTAMP + (?::interval)",
        translated,
        flags=re.IGNORECASE,
    )
    translated = _replace_qmark_placeholders(translated)
    return translated


def _split_sql_script(script: str) -> list[str]:
    """Split a DDL script on semicolons outside strings/comments."""
    statements: list[str] = []
    current: list[str] = []
    state = "normal"
    index = 0
    while index < len(script):
        char = script[index]
        nxt = script[index + 1] if index + 1 < len(script) else ""
        current.append(char)
        if state == "normal":
            if char == "'":
                state = "single"
            elif char == '"':
                state = "double"
            elif char == "-" and nxt == "-":
                state = "line_comment"
                current.append(nxt)
                index += 1
            elif char == "/" and nxt == "*":
                state = "block_comment"
                current.append(nxt)
                index += 1
            elif char == ";":
                statement = "".join(current).strip()
                if statement and statement != ";":
                    statements.append(statement)
                current = []
        elif state == "single":
            if char == "'":
                if nxt == "'":
                    current.append(nxt)
                    index += 1
                else:
                    state = "normal"
        elif state == "double":
            if char == '"':
                if nxt == '"':
                    current.append(nxt)
                    index += 1
                else:
                    state = "normal"
        elif state == "line_comment":
            if char == "\n":
                state = "normal"
        elif state == "block_comment":
            if char == "*" and nxt == "/":
                current.append(nxt)
                index += 1
                state = "normal"
        index += 1
    tail = "".join(current).strip()
    if tail:
        statements.append(tail)
    return statements


class EmptyCursor:
    rowcount = 0
    lastrowid = 0

    def fetchall(self) -> list[dict]:
        return []

    def fetchone(self):
        return None


class PostgreSQLCursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self.lastrowid = 0

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def fetchall(self):
        return self._cursor.fetchall()

    def fetchone(self):
        return self._cursor.fetchone()

    def __iter__(self):
        return iter(self._cursor)


class PostgreSQLCompatConnection:
    def __init__(self, connection):
        self._connection = connection

    def _pragma_table_info(self, sql: str):
        match = re.match(
            r"^\s*PRAGMA\s+table_info\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)\s*;?\s*$",
            sql,
            flags=re.IGNORECASE,
        )
        if not match:
            return None
        table = match.group(1)
        cursor = self._connection.execute(
            """
            SELECT ordinal_position - 1 AS cid,
                   column_name AS name,
                   data_type AS type,
                   CASE WHEN is_nullable='NO' THEN 1 ELSE 0 END AS notnull,
                   column_default AS dflt_value,
                   0 AS pk
            FROM information_schema.columns
            WHERE table_schema=current_schema() AND table_name=%s
            ORDER BY ordinal_position
            """,
            (table,),
        )
        rows = cursor.fetchall()
        pk_cursor = self._connection.execute(
            """
            SELECT a.attname AS name
            FROM pg_index i
            JOIN pg_attribute a
              ON a.attrelid=i.indrelid AND a.attnum=ANY(i.indkey)
            WHERE i.indrelid=%s::regclass AND i.indisprimary
            """,
            (table,),
        )
        primary = {str(item["name"]) for item in pk_cursor.fetchall()}
        for item in rows:
            item["pk"] = 1 if str(item["name"]) in primary else 0
        return _StaticCursor(rows)

    def execute(self, sql: str, params=()):
        pragma = self._pragma_table_info(str(sql))
        if pragma is not None:
            return pragma
        if re.match(r"^\s*PRAGMA\b", str(sql), flags=re.IGNORECASE):
            return EmptyCursor()
        cursor = self._connection.execute(translate_sql(str(sql)), params)
        return PostgreSQLCursor(cursor)

    def executemany(self, sql: str, seq_of_params: Iterable):
        cursor = self._connection.cursor()
        cursor.executemany(translate_sql(str(sql)), seq_of_params)
        return PostgreSQLCursor(cursor)

    def executescript(self, script: str):
        result: Any = EmptyCursor()
        for statement in _split_sql_script(script):
            result = self.execute(statement)
        return result

    def commit(self):
        return self._connection.commit()

    def rollback(self):
        return self._connection.rollback()

    def close(self):
        # Pool ownership remains outside this compatibility wrapper.
        return None


class _StaticCursor:
    def __init__(self, rows: list[dict]):
        self._rows = rows
        self.rowcount = len(rows)
        self.lastrowid = 0

    def fetchall(self):
        return list(self._rows)

    def fetchone(self):
        return self._rows[0] if self._rows else None

    def __iter__(self):
        return iter(self._rows)


def _pool_configure(connection) -> None:
    # Keep all application timestamps in UTC while preserving the current
    # string-based schema during the compatibility migration.
    connection.execute("SET TIME ZONE 'UTC'")
    connection.commit()


def get_pool():
    global _POOL
    with _POOL_LOCK:
        if _POOL is not None and not getattr(_POOL, "closed", False):
            return _POOL
        _psycopg, dict_row, ConnectionPool = _require_psycopg()
        cfg = load_database_config()
        settings = postgresql_settings(cfg)
        conninfo = (
            f"host={settings['host']} port={settings['port']} dbname={settings['dbname']} "
            f"user={settings['user']} password={settings['password']} "
            f"sslmode={settings['sslmode']} connect_timeout={settings['connect_timeout']}"
        )
        _POOL = ConnectionPool(
            conninfo=conninfo,
            min_size=int(cfg.get("postgresql_pool_min", 2)),
            max_size=int(cfg.get("postgresql_pool_max", 12)),
            kwargs={"row_factory": dict_row},
            configure=_pool_configure,
            timeout=float(settings["connect_timeout"] + 5),
            open=True,
            name="marketplace_hub",
        )
        return _POOL


def close_pool() -> None:
    global _POOL
    with _POOL_LOCK:
        if _POOL is not None:
            try:
                _POOL.close()
            except Exception:
                pass
            _POOL = None


atexit.register(close_pool)


@contextmanager
def connect():
    pool = get_pool()
    with pool.connection() as connection:
        yield PostgreSQLCompatConnection(connection)


def pool_stats() -> dict[str, Any]:
    try:
        stats = get_pool().get_stats()
        return dict(stats or {})
    except Exception:
        return {}


def test_connection(config: dict[str, Any] | None = None) -> dict[str, Any]:
    psycopg, dict_row, _ConnectionPool = _require_psycopg()
    settings = postgresql_settings(config)
    with psycopg.connect(**settings, row_factory=dict_row) as connection:
        row = connection.execute(
            "SELECT current_database() AS database, current_user AS username, "
            "current_setting('server_version') AS version"
        ).fetchone()
        return dict(row or {})


def table_has_column(connection: PostgreSQLCompatConnection, table: str, column: str) -> bool:
    cursor = connection._connection.execute(
        """
        SELECT 1 FROM information_schema.columns
        WHERE table_schema=current_schema() AND table_name=%s AND column_name=%s
        LIMIT 1
        """,
        (table, column),
    )
    return cursor.fetchone() is not None


def insert_returning_id(connection: PostgreSQLCompatConnection, sql: str, params=()) -> int:
    raw = str(sql).strip()
    match = re.match(
        r"^INSERT\s+(?:OR\s+IGNORE\s+)?INTO\s+([A-Za-z_][A-Za-z0-9_]*)\b",
        raw,
        flags=re.IGNORECASE,
    )
    translated = translate_sql(raw)
    if not match:
        cursor = connection._connection.execute(translated, params)
        return max(0, int(cursor.rowcount or 0))
    table = match.group(1)
    if not table_has_column(connection, table, "id"):
        cursor = connection._connection.execute(translated, params)
        return 0
    if not re.search(r"\bRETURNING\b", translated, flags=re.IGNORECASE):
        semicolon = ";" if translated.rstrip().endswith(";") else ""
        body = translated.rstrip()
        if semicolon:
            body = body[:-1].rstrip()
        translated = f"{body} RETURNING id{semicolon}"
    cursor = connection._connection.execute(translated, params)
    found = cursor.fetchone()
    if not found:
        return 0
    if isinstance(found, dict):
        return int(found.get("id") or 0)
    return int(found[0] or 0)
