"use client";
import { useEffect, useMemo, useState } from "react";
import { WorkspacePage } from "@/components/WorkspacePage";
import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { Icon } from "@/components/Icon";
import { useWorkspace } from "@/components/WorkspaceProvider";
import { api } from "@/lib/api";
import type { Job } from "@/lib/types";
function Body(){const{seller}=useWorkspace();const[jobs,setJobs]=useState<Job[]>([]);const[filter,setFilter]=useState("all");useEffect(()=>{if(!seller)return;let live=true;const load=()=>api<Job[]>(`/jobs?seller_id=${seller.id}&limit=50`).then(x=>live&&setJobs(x)).catch(()=>live&&setJobs([]));void load();const id=setInterval(load,5000);return()=>{live=false;clearInterval(id)}},[seller?.id]);const visible=useMemo(()=>filter==="all"?jobs:jobs.filter(j=>filter==="active"?["queued","running"].includes(j.status):j.status===filter),[jobs,filter]);const running=jobs.filter(j=>["queued","running"].includes(j.status)).length;return <><PageHeader title="Attività" description="Worker, sincronizzazioni e processi lunghi continuano anche mentre navighi nel SaaS." action={<span className="liveIndicator"><i/>{running?`${running} in esecuzione`:"Worker monitorato"}</span>}/><div className="filterTabs"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Tutte <span>{jobs.length}</span></button><button className={filter==="active"?"active":""} onClick={()=>setFilter("active")}>In corso <span>{running}</span></button><button className={filter==="done"?"active":""} onClick={()=>setFilter("done")}>Completate</button><button className={filter==="error"?"active":""} onClick={()=>setFilter("error")}>Errori</button></div><section className="panel noPad">{visible.length?<div className="jobTable"><div className="jobTableHead"><span>Attività</span><span>Avanzamento</span><span>Stato</span><span>Avviata</span></div>{visible.map(j=><div className="jobTableRow" key={j.job_id}><div className="jobIdentity"><span className="jobKindIcon"><Icon name="activity" size={17}/></span><div><b>{j.kind.replaceAll("_"," ")}</b><small>{j.message||j.error||j.job_id}</small></div></div><div className="jobProgressCell"><div className="progress"><i style={{width:`${Math.max(j.status==="done"?100:2,j.progress_pct)}%`}}/></div><span>{Math.round(j.status==="done"?100:j.progress_pct)}%</span></div><StatusBadge status={j.status}/><span className="jobTime">{formatDate(j.started_at||j.created_at)}</span></div>)}</div>:<div className="emptyPro"><Icon name="activity" size={24}/><div><b>Nessuna attività in questa vista</b><p>I processi background compariranno qui automaticamente.</p></div></div>}</section></>}
function formatDate(value:string){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString("it-IT",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}
export default function Page(){return <WorkspacePage><Body/></WorkspacePage>}
