from __future__ import annotations

import base64
import binascii
import hashlib
import hmac

from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerificationError, VerifyMismatchError

_hasher = PasswordHasher(time_cost=3, memory_cost=65536, parallelism=4)


class WeakPasswordError(ValueError):
    pass


def validate_password(password: str) -> None:
    if len(password) < 12:
        raise WeakPasswordError("La password deve contenere almeno 12 caratteri.")
    if not any(character.isupper() for character in password):
        raise WeakPasswordError("La password deve contenere almeno una lettera maiuscola.")
    if not any(character.islower() for character in password):
        raise WeakPasswordError("La password deve contenere almeno una lettera minuscola.")
    if not any(character.isdigit() for character in password):
        raise WeakPasswordError("La password deve contenere almeno un numero.")


def hash_password(password: str) -> str:
    validate_password(password)
    return _hasher.hash(password)


def verify_password(password_hash: str, password: str) -> bool:
    if password_hash.startswith("pbkdf2_sha256$"):
        return _verify_legacy_password(password_hash, password)
    try:
        return _hasher.verify(password_hash, password)
    except (InvalidHashError, VerificationError, VerifyMismatchError):
        return False


def _verify_legacy_password(password_hash: str, password: str) -> bool:
    """Read the exact format generated by the previous SaaS; never write it."""
    try:
        algorithm, iterations, salt_text, digest_text = password_hash.split("$")
        if algorithm != "pbkdf2_sha256" or iterations != "390000":
            return False
        if len(salt_text) != 24 or len(digest_text) != 43:
            return False
        salt = base64.b64decode(salt_text, altchars=b"-_", validate=True)
        expected = base64.b64decode(digest_text + "=", altchars=b"-_", validate=True)
        if len(salt) != 18 or len(expected) != 32:
            return False
        actual = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, 390_000)
        return hmac.compare_digest(actual, expected)
    except (ValueError, TypeError, binascii.Error):
        return False


def password_needs_rehash(password_hash: str) -> bool:
    return password_hash.startswith("pbkdf2_sha256$") or _hasher.check_needs_rehash(password_hash)


def rehash_verified_password(password: str) -> str:
    """Upgrade a verified credential without imposing a new password-creation policy."""
    return _hasher.hash(password)
